app_login:
    path: /login
    controller: App\Controller\SecurityController::login

main_page:
    path: /
    controller: App\Controller\MainPageController::index


app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# config/routes.yaml
#
#show_post:
#    path: /post/{id}
#    controller: App\Controller\PostController::show

add_post:
    path: /post/add
    controller: App\Controller\PostController::add

post_show:
    path: /post/{id}
    controller: App\Controller\PostController::show

post_delete:
    path: /post/delete/{id}
    controller: App\Controller\PostController::delete
    methods: [POST, DELETE]

post_edit:
    path: /post/{id}/edit
    controller: App\Controller\PostController::edit
    methods: [GET, POST]

category_list:
    path: /categories
    controller: App\Controller\CategoryController::list

category_edit:
    path: /category/{id}/edit
    controller: App\Controller\CategoryController::edit
    methods: [GET]

category_delete:
    path: /category/{id}/delete
    controller: App\Controller\CategoryController::delete
    methods: [POST, DELETE]

category_show:
    path: /category/{id}
    controller: App\Controller\CategoryController::show

category_create:
    path: /category/create
    controller: App\Controller\CategoryController::create
    methods: [GET, POST]