app_login:
    path: /login
    controller: App\Controller\SecurityController::login

main_page:
    path: /
    controller: App\Controller\MainPageController::index


app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout


add_post:
    path: /post/add
    controller: App\Controller\PostController::add

post_show:
    path: /post/{id}
    controller: App\Controller\PostController::show

post_delete:
    path: /post/delete/{id}
    controller: App\Controller\PostController::delete
    methods: [DELETE]

post_edit: #done
    path: /post/{id}/edit
    controller: App\Controller\PostController::edit
    methods: [GET, PUT]

category_list:
    path: /categories
    controller: App\Controller\CategoryController::list

category_edit:
    path: /category/{id}/edit #done
    controller: App\Controller\CategoryController::edit
    methods: [GET,PUT]

category_delete:
    path: /category/{id}/delete
    controller: App\Controller\CategoryController::delete
    methods: [DELETE]

category_new:
    path: /category/news
    controller: App\Controller\CategoryController::new
    methods: [GET, POST]

comment_delete:
    path: /comment/delete/{id}
    controller: App\Controller\CommentController::delete
    methods: [DELETE,GET]

post_list:
    path: /posts
    controller: App\Controller\PostController::list
    methods: [GET]

admin_edit_user:
    path: /admin/edit-user
    controller: App\Controller\MainPageController::editUser
    methods: [PUT,GET]
